version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: './client/Dockerfile'
    ports:
      - '127.0.0.1:${PORT}:80'
    command: ['nginx', '-g', 'daemon off;']
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: './server/Dockerfile'
    command: ['node', 'index.js']
    environment:
      - ELASTICSEARCH_HOST=es01
      - ELASTICSEARCH_PORT=9200
    depends_on:
    - es01
    - es02
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data

volumes:
  data01:
    driver: local
  data02:
    driver: local

