const PORT = process.env.PORT || 3001;
const ELASTICSEARCH_HOST = process.env.ELASTICSEARCH_HOST || "localhost";
const ELASTICSEARCH_PORT = process.env.ELASTICSEARCH_PORT || 9200;

exports.PORT = PORT;
exports.ELASTICSEARCH_HOST = ELASTICSEARCH_HOST;
exports.ELASTICSEARCH_PORT = ELASTICSEARCH_PORT;
